import React,{useEffect,useMemo,useState}from"react";
import{Minus,Plus,ShieldCheck,ShoppingBag}from"lucide-react";
import{Link,useLocation,useNavigate}from"react-router-dom";
import api,{imgUrl}from"../api/api";
import{useAuth}from"../context/AuthContext";
import Auth from"./Auth";
import{useToast}from"../context/ToastContext";

export default function Checkout(){
 const{user}=useAuth(),{state}=useLocation(),navigate=useNavigate(),toast=useToast();
 const[address,setAddress]=useState({state:"Tamil Nadu"}),[paymentMethod,setPaymentMethod]=useState("Razorpay"),[cartItems,setCartItems]=useState([]),[buyNowQuantity,setBuyNowQuantity]=useState(state?.quantity||1),[placingOrder,setPlacingOrder]=useState(false);
 useEffect(()=>{if(!state?.buyNow&&user)api.get("/cart").then(r=>setCartItems(r.data)).catch(()=>setCartItems([]))},[state?.buyNow,user]);
 const checkoutItems=useMemo(()=>state?.buyNow?[{product:state.buyNow,quantity:buyNowQuantity,size:state.size||"",color:state.color||""}]:cartItems,[state,buyNowQuantity,cartItems]);
 const amount=checkoutItems.reduce((s,i)=>s+Number(i.product?.discountPrice||i.product?.price||0)*Number(i.quantity||1),0);
 if(!user)return <Auth/>;
 const change=e=>setAddress(p=>({...p,[e.target.name]:e.target.value}));
 const updateQty=async(item,qty)=>{const next=Math.max(1,qty);if(state?.buyNow)return setBuyNowQuantity(next);await api.put(`/cart/${item._id}`,{quantity:next});setCartItems(c=>c.map(i=>i._id===item._id?{...i,quantity:next}:i))};
 const razorpay=async()=>{if(!window.Razorpay){const ok=await new Promise(resolve=>{const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.body.appendChild(s)});if(!ok)throw new Error("Razorpay SDK failed to load")};const{data:o}=await api.post("/payment/create-order",{amount});return new Promise(resolve=>new window.Razorpay({key:o.keyId,amount:o.amount,currency:o.currency||"INR",name:"Women's Styles",order_id:o.id,prefill:{name:address.fullName||user.name,contact:address.phone,email:user.email},theme:{color:"#1261d6"},handler:async r=>{try{resolve((await api.post("/payment/verify",r)).data)}catch{resolve(false)}},modal:{ondismiss:()=>resolve(false)}}).open())};
 const placeOrder=async e=>{e.preventDefault();if(!checkoutItems.length)return toast.error("No items in checkout");setPlacingOrder(true);try{let paymentStatus="Pending",razorpayPaymentId,paymentProof;if(paymentMethod==="Razorpay"){const p=await razorpay();if(!p?.verified){toast.info("Payment not completed");return}paymentStatus="Paid";razorpayPaymentId=p.paymentId;paymentProof=p.paymentProof}const items=checkoutItems.map(i=>({product:i.product._id,name:i.product.name,price:i.product.discountPrice||i.product.price,quantity:i.quantity||1,size:i.size,color:i.color,image:i.product.images?.[0]}));await api.post("/orders",{items,address,amount,paymentMethod,paymentStatus,razorpayPaymentId,paymentProof});toast.success("Order placed successfully");navigate("/orders")}catch(err){toast.error(err.response?.data?.message||err.message||"Unable to place order")}finally{setPlacingOrder(false)}};
 return <main className="checkout-page"><div className="checkout-brand"><Link to="/">Women's Styles</Link><Link to="/cart" className="checkout-cart-link" aria-label="View cart"><ShoppingBag/><span>{checkoutItems.reduce((sum,item)=>sum+Number(item.quantity||1),0)}</span></Link></div><form onSubmit={placeOrder} className="checkout-grid">
  <section className="checkout-form">
   <div className="checkout-heading"><h2>Contact</h2><span>{user.email}</span></div><input className="checkout-input" value={user.email||""} readOnly/><label className="checkout-check"><input type="checkbox"/> Email me with news and offers</label>
   <h2>Delivery</h2><div className="checkout-fields"><label className="field-wide"><small>Country/Region</small><select><option>India</option></select></label><input name="fullName" onChange={change} placeholder="Full name" required/><input name="phone" onChange={change} placeholder="Mobile number" required/><input className="field-wide" name="address" onChange={change} placeholder="Address" required/><input className="field-wide" name="alternatePhone" onChange={change} placeholder="Apartment, suite, etc. (optional)"/><input name="city" onChange={change} placeholder="City" required/><input name="district" onChange={change} placeholder="District" required/><label><small>State</small><select name="state" value={address.state} onChange={change}><option>Tamil Nadu</option><option>Kerala</option><option>Karnataka</option></select></label><input name="pincode" onChange={change} placeholder="PIN code" required/></div>
   <label className="checkout-check"><input type="checkbox"/> Save this information for next time</label><h2>Shipping method</h2><div className="shipping-note">Free standard shipping on all orders</div>
   <h2>Payment</h2><p className="checkout-muted">All transactions are secure and encrypted.</p><div className="payment-box"><label className={paymentMethod==="Razorpay"?"active":""}><input type="radio" checked={paymentMethod==="Razorpay"} onChange={()=>setPaymentMethod("Razorpay")}/><b>Razorpay Secure (UPI, Cards, Wallets)</b><span>UPI &nbsp; VISA &nbsp; ●●</span></label>{paymentMethod==="Razorpay"&&<p>You'll be redirected to Razorpay Secure to complete your purchase.</p>}<label className={paymentMethod==="Cash on Delivery"?"active":""}><input type="radio" checked={paymentMethod==="Cash on Delivery"} onChange={()=>setPaymentMethod("Cash on Delivery")}/><b>Cash on Delivery</b></label></div>
   <h3>Billing address</h3><div className="billing-box"><label><input type="radio" defaultChecked/> Same as shipping address</label><label><input type="radio"/> Use a different billing address</label></div><button disabled={placingOrder} className="checkout-pay">{placingOrder?"Please wait...":paymentMethod==="Razorpay"?"Pay now":"Place order"}</button><p className="secure-note"><ShieldCheck/> Secure checkout</p>
  </section>
  <aside className="checkout-summary"><div className="summary-inner">{checkoutItems.map(item=><div className="checkout-product" key={item._id||item.product?._id}><div><img src={imgUrl(item.product?.images?.[0])}/><b>{item.quantity||1}</b></div><span><strong>{item.product?.name}</strong><small>{[item.size,item.color].filter(Boolean).join(" / ")}</small><i><button type="button" onClick={()=>updateQty(item,(item.quantity||1)-1)}><Minus/></button>{item.quantity||1}<button type="button" onClick={()=>updateQty(item,(item.quantity||1)+1)}><Plus/></button></i></span><em>₹{Number(item.product?.discountPrice||item.product?.price||0).toLocaleString("en-IN")}</em></div>)}<div className="coupon"><input placeholder="Discount code or gift card"/><button type="button">Apply</button></div><div className="summary-lines"><p><span>Subtotal</span><b>₹{amount.toLocaleString("en-IN")}</b></p><p><span>Shipping</span><span>Free</span></p><h3><span>Total</span><b><small>INR</small> ₹{amount.toLocaleString("en-IN")}</b></h3></div></div></aside>
 </form></main>;
}
