import React,{useEffect,useRef,useState}from'react';
import{Plus,Trash2,Save,Tags,TicketPercent,Megaphone,Mail,Send}from'lucide-react';
import api from'../../api/api';
import{useToast}from'../../context/ToastContext';

const box="border border-white/10 bg-white/[0.04] p-5";
const input="w-full border border-white/10 bg-white/[0.05] px-3 py-2.5 text-sm text-white outline-none";
const label="text-xs font-bold text-white/55";
const emptyOffer={enabled:false,label:'',message:'',couponCode:'',buttonText:'Shop Now',buttonUrl:'/dress'};
const emptyCoupon={code:'',description:'',type:'percentage',value:'',minimumOrder:0,maximumDiscount:0,firstOrderOnly:false,active:true};

export default function AdminCommerce(){
 const[data,setData]=useState({categories:[],coupons:[],subscribers:[],offer:emptyOffer});
 const[cat,setCat]=useState({name:'',parent:''}),[coupon,setCoupon]=useState(emptyCoupon);
 const[selected,setSelected]=useState([]),[campaign,setCampaign]=useState({subject:'',message:''}),[sending,setSending]=useState(false);const toast=useToast();
 const knownSubscribers=useRef(null);
 const load=async(showError=true)=>{try{const r=await api.get('/store/admin/catalog');const ids=new Set(r.data.subscribers.map(s=>s._id));if(knownSubscribers.current){const newcomers=r.data.subscribers.filter(s=>!knownSubscribers.current.has(s._id));if(newcomers.length)toast.info(`${newcomers.length} new subscriber${newcomers.length===1?'':'s'} joined`)}knownSubscribers.current=ids;setData({...r.data,offer:{...emptyOffer,...(r.data.offer||{})}})}catch(e){if(showError)toast.error(e.response?.data?.message||'Unable to load catalogue')}};
 useEffect(()=>{load();const timer=setInterval(()=>load(false),15000);return()=>clearInterval(timer)},[]);
 const run=async(fn,success='Saved successfully')=>{try{await fn();toast.success(success);await load();return true}catch(e){toast.error(e.response?.data?.message||'Unable to save');return false}};
 const active=data.subscribers.filter(s=>s.active),allSelected=active.length>0&&active.every(s=>selected.includes(s._id));
 const toggle=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const send=async e=>{e.preventDefault();setSending(true);try{const{data:r}=await api.post('/store/admin/subscribers/send',{subscriberIds:selected,subject:campaign.subject,message:campaign.message});toast.success(r.message);setCampaign({subject:'',message:''});setSelected([]);await load()}catch(err){toast.error(err.response?.data?.message||'Unable to send message')}finally{setSending(false)}};
 const field=(name,title,props={})=><label className={label}>{title}<input {...props} className={`${input} mt-1`} value={props.value??coupon[name]} onChange={props.onChange||((e)=>setCoupon({...coupon,[name]:e.target.value}))}/></label>;

 return <div className="space-y-6 pb-16">
  <div><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#d6b36a]">Store controls</p><h1 className="mt-2 text-3xl font-black">Women’s Fashion Catalogue</h1><p className="mt-1 text-sm text-white/45">Categories, offers, coupons and subscribers — all controlled here.</p></div>

  <section className={box}><h2 className="mb-4 flex items-center gap-2 text-xl font-black"><Tags/>Categories</h2><form onSubmit={async e=>{e.preventDefault();if(await run(()=>api.post('/store/admin/categories',cat),'Category added'))setCat({name:'',parent:''})}} className="grid items-end gap-3 sm:grid-cols-[1fr_1fr_auto]"><label className={label}>Category name<input className={`${input} mt-1`} required placeholder="e.g. Sarees" value={cat.name} onChange={e=>setCat({...cat,name:e.target.value})}/></label><label className={label}>Parent category (optional)<input className={`${input} mt-1`} placeholder="e.g. Ethnic Wear" value={cat.parent} onChange={e=>setCat({...cat,parent:e.target.value})}/></label><button className="btn-primary"><Plus size={16}/> Add</button></form><div className="mt-4 flex flex-wrap gap-2">{data.categories.map(c=><span key={c._id} className="flex items-center gap-2 border border-white/10 px-3 py-2 text-xs font-bold">{c.name}{c.parent&&` · ${c.parent}`}<button aria-label={`Delete ${c.name}`} onClick={()=>confirm('Delete category?')&&run(()=>api.delete('/store/admin/categories/'+c._id),'Category deleted')}><Trash2 size={13}/></button></span>)}</div></section>

  <section className={box}><h2 className="mb-1 flex items-center gap-2 text-xl font-black"><Megaphone/>Top offer banner</h2><p className="mb-5 text-xs text-white/45">Fill the text shown in the website top strip. Coupon code must match an active coupon below.</p><div className="grid gap-4 sm:grid-cols-2">{[['label','Small label','LIMITED OFFER'],['message','Main offer message','Flat 20% off on selected styles'],['couponCode','Active coupon code','NEW20'],['buttonText','Button text','Shop Now'],['buttonUrl','Button link','/dress']].map(([k,l,p])=><label key={k} className={label}>{l}<input className={`${input} mt-1`} placeholder={p} value={data.offer[k]||''} onChange={e=>setData({...data,offer:{...data.offer,[k]:e.target.value}})}/></label>)}<label className="flex items-center gap-2 self-end py-3 text-sm font-bold"><input type="checkbox" checked={!!data.offer.enabled} onChange={e=>setData({...data,offer:{...data.offer,enabled:e.target.checked}})}/> Show banner on website</label></div><button onClick={()=>run(()=>api.put('/store/admin/offer',data.offer),'Offer banner saved')} className="btn-primary mt-4"><Save size={16}/> Save banner</button></section>

  <section className={box}><h2 className="mb-1 flex items-center gap-2 text-xl font-black"><TicketPercent/>Coupons</h2><p className="mb-5 text-xs text-white/45">Percentage reduces that percent from the eligible order total. Fixed amount reduces exactly the entered rupee value.</p><form onSubmit={async e=>{e.preventDefault();if(await run(()=>api.post('/store/admin/coupons',coupon),'Coupon created'))setCoupon(emptyCoupon)}} className="grid items-end gap-3 sm:grid-cols-2 lg:grid-cols-3">
   {field('code','Coupon name / code',{required:true,placeholder:'e.g. NEW20'})}
   {field('description','Customer-facing description',{placeholder:'e.g. New user 20% off'})}
   <label className={label}>Discount type<select className={`${input} mt-1`} value={coupon.type} onChange={e=>setCoupon({...coupon,type:e.target.value})}><option className="bg-[#15120f]" value="percentage">Percentage (%)</option><option className="bg-[#15120f]" value="fixed">Fixed amount (₹)</option></select></label>
   {field('value',coupon.type==='percentage'?'Discount percentage':'Discount amount (₹)',{required:true,type:'number',min:'0',max:coupon.type==='percentage'?'100':undefined,step:'0.01',placeholder:coupon.type==='percentage'?'e.g. 20':'e.g. 200'})}
   {field('minimumOrder','Eligible minimum order amount (₹)',{required:true,type:'number',min:'0',step:'0.01',placeholder:'e.g. 3000'})}
   {field('maximumDiscount','Maximum discount cap (₹)',{type:'number',min:'0',step:'0.01',placeholder:'0 means no limit'})}
   <label className="flex items-center gap-2 py-3 text-sm font-bold"><input type="checkbox" checked={coupon.firstOrderOnly} onChange={e=>setCoupon({...coupon,firstOrderOnly:e.target.checked})}/> First order / new users only</label>
   <button className="btn-primary"><Plus size={16}/> Create coupon</button>
  </form><div className="mt-5 grid gap-2">{data.coupons.map(c=><div key={c._id} className="flex items-center justify-between border border-white/10 p-3"><div><b>{c.code}</b>{c.description&&<p className="text-xs text-white/70">{c.description}</p>}<p className="text-xs text-white/45">{c.type==='percentage'?`${c.value}% off`:`₹${c.value} off`} · Eligible above ₹{c.minimumOrder||0}{c.firstOrderOnly?' · First order only':''} · Used {c.usedCount||0}</p></div><button aria-label={`Delete coupon ${c.code}`} onClick={()=>confirm('Delete coupon?')&&run(()=>api.delete('/store/admin/coupons/'+c._id),'Coupon deleted')}><Trash2 size={16}/></button></div>)}</div></section>

  <section className={box}><h2 className="flex items-center gap-2 text-xl font-black"><Mail/>Subscribers <span className="text-sm text-[#d6b36a]">{active.length} active</span></h2><p className="mt-1 text-xs text-white/45">Select one or more customers, write your offer, and send it directly to their email.</p><div className="mt-4 grid gap-5 lg:grid-cols-[1fr_1.15fr]"><div className="max-h-80 overflow-auto border border-white/10"><label className="flex gap-3 border-b border-white/10 bg-white/[0.05] p-3 text-sm font-bold"><input type="checkbox" checked={allSelected} onChange={()=>setSelected(allSelected?[]:active.map(s=>s._id))}/> Select all active</label>{data.subscribers.map(s=><div key={s._id} className="flex items-center justify-between border-b border-white/10 p-3 text-sm"><label className={`flex min-w-0 items-center gap-3 ${!s.active?'opacity-40':''}`}><input type="checkbox" disabled={!s.active} checked={selected.includes(s._id)} onChange={()=>toggle(s._id)}/><span className="truncate">{s.email}</span></label><button onClick={()=>run(()=>api.patch('/store/admin/subscribers/'+s._id,{active:!s.active}),s.active?'Subscriber disabled':'Subscriber enabled')} className={s.active?'text-emerald-400':'text-white/35'}>{s.active?'Active':'Inactive'}</button></div>)}</div><form onSubmit={send} className="grid content-start gap-3"><div className="text-xs font-bold text-[#d6b36a]">{selected.length} recipient{selected.length===1?'':'s'} selected</div><label className={label}>Email subject<input required className={`${input} mt-1`} placeholder="Weekend special — 20% off" value={campaign.subject} onChange={e=>setCampaign({...campaign,subject:e.target.value})}/></label><label className={label}>Offer message<textarea required rows="6" className={`${input} mt-1 resize-y`} placeholder="Hi! Enjoy 20% off with code NEW20." value={campaign.message} onChange={e=>setCampaign({...campaign,message:e.target.value})}/></label><button disabled={sending||!selected.length} className="btn-primary justify-self-start"><Send size={16}/>{sending?' Sending...':' Send email'}</button></form></div></section>
 </div>;
}
